services:
  trinitycore:
    build: .
    environment:
      - PUBLIC_IP_ADDRESS=127.0.0.1
    volumes:
      - ./server/data:/app/server/data
      - ./client:/app/client # Mount the client directory    
      - server_logs:/app/server/logs      
      - type: tmpfs
        target: /app/tmp
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8085:8085" # World server
      - "3724:3724" # Auth server
      - "3000:3000" # Web server
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: "8g"
        reservations:
          cpus: "4.0"
          memory: "8g"
  database:
    image: mysql:8.4.4
    environment:
      MYSQL_ROOT_PASSWORD: trinityroot
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ptrinityroot"]
      interval: 10s
      timeout: 5s 
      retries: 3
volumes:
  db_data:
  server_logs: